# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: checker.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class Result(betterproto.Enum):
    OK = 0
    ERROR = 1


@dataclass(eq=False, repr=False)
class Point(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class Polygon(betterproto.Message):
    points: List["Point"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CheckRequest(betterproto.Message):
    polygon: "Polygon" = betterproto.message_field(1)
    point: "Point" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CheckResponse(betterproto.Message):
    result: "Result" = betterproto.enum_field(1)
    is_inside: bool = betterproto.bool_field(2)


class CheckerStub(betterproto.ServiceStub):
    async def check(
        self,
        check_request: "CheckRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CheckResponse":
        return await self._unary_unary(
            "/checker.Checker/Check",
            check_request,
            CheckResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class CheckerBase(ServiceBase):
    async def check(self, check_request: "CheckRequest") -> "CheckResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_check(
        self, stream: "grpclib.server.Stream[CheckRequest, CheckResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.check(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/checker.Checker/Check": grpclib.const.Handler(
                self.__rpc_check,
                grpclib.const.Cardinality.UNARY_UNARY,
                CheckRequest,
                CheckResponse,
            ),
        }
